image:
  repository: quay.io/gitops-cookbook/music
  tag: "1.0.0"
  pullPolicy: Always
  containerPort: 8080

replicaCount: 1

postgresql:
  server: jdbc:postgresql://music-db-postgresql:5432/mydb
  auth:
    username: my-default
    password: postgres
    database: mydb  
  secretName: music-db-postgresql
  secretKey: password
