# Variables
K8SV = '1.33.2-1.1' # Kubernetes Version : apt list -a kubelet , ex) 1.32.5-1.1
CONTAINERDV = '1.7.27-1' # Containerd Version : apt list -a containerd.io , ex) 1.6.33-1
CILIUMV = '1.17.6' # Cilium CNI Version : https://github.com/cilium/cilium/tags

N = 1 # max number of worker nodes
MASTER_IP = "192.168.10.100"
WORKER_IP_PREFIX = "192.168.10.10"


# Base Image  https://portal.cloud.hashicorp.com/vagrant/discover/bento/ubuntu-24.04
## Rocky linux Image https://portal.cloud.hashicorp.com/vagrant/discover/rockylinux
BOX_IMAGE = "bento/ubuntu-24.04"
BOX_VERSION = "202502.21.0"

Vagrant.configure("2") do |config|
#-ControlPlane Node
  config.ssh.insert_key = false # KKamJi Add -> insecure key 재사용
  config.vm.define "cilium-m1" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/Cilium-Lab"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.name = "cilium-m1"
      vb.cpus = 3
      vb.memory = 3072
      vb.linked_clone = true
    end
    subconfig.vm.host_name = "cilium-m1"
    subconfig.vm.network "private_network", ip: MASTER_IP
    subconfig.vm.network "forwarded_port", guest: 22, host: 60000, auto_correct: true, id: "ssh"
    # KKamJi Add
    subconfig.vm.network "forwarded_port", guest: 6443, host: 56444, auto_correct: true, id: "api-server" # 추가 api-server
    subconfig.vm.synced_folder "./", "/vagrant", disabled: true
    # KKamJI Add
    subconfig.vm.provision "file", run: "once", source: "./configurations/", destination: "/tmp/" 
    # subconfig.vm.synced_folder "./configurations", "/opt/configurations", disabled: true
    subconfig.vm.provision "shell", path: "init_cfg.sh", args: [ K8SV, CONTAINERDV]
    subconfig.vm.provision "shell", path: "k8s-ctr.sh", args: [ MASTER_IP, N , CILIUMV , K8SV ]
  end

#-Worker Nodes Subnet1
  (1..N).each do |i|
    config.vm.define "cilium-w#{i}" do |subconfig|
      worker_ip = "#{WORKER_IP_PREFIX}#{i}"
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--groups", "/Cilium-Lab"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.name = "cilium-w#{i}"
        vb.cpus = 3
        vb.memory = 3072
        vb.linked_clone = true
      end
      subconfig.vm.host_name = "cilium-w#{i}"
      subconfig.vm.network "private_network", ip: worker_ip
      subconfig.vm.network "forwarded_port", guest: 22, host: "6000#{i}", auto_correct: true, id: "ssh"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      # KKamJI Add
      subconfig.vm.provision "file", run: "once", source: "./configurations/", destination: "/tmp/" 
      # subconfig.vm.synced_folder "./configurations", "/opt/configurations", disabled: true
      subconfig.vm.provision "shell", path: "init_cfg.sh", args: [ K8SV, CONTAINERDV]
      subconfig.vm.provision "shell", path: "k8s-w.sh", args: worker_ip
    end
  end
end
